### ISSUE TITLE
ResourceManager Memory Leak

### ISSUE THREAD

**Issue by retrogamer500** [LEMEMETEAM/DabEngine#6]
Was just browsing through the code and I noticed this:

ResourceManager's InMemoryCache removes resources after 1000 seconds. This can cause a memory leak as some resources (like textures) use memory on the GPU, and this memory is not reclaimed.

It doesn't look like simply calling dispose() while cleaning up the cache is a solution either. Since there may be entities with references to this texture, this would cause OpenGL errors if they try to render their deleted texture.

**Comment by LEMEMETEAM** [comment]
#
